/*
Agent Manager Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spec

import (
	"encoding/json"
	"time"
)

// checks if the A2AAgentCardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &A2AAgentCardResponse{}

// A2AAgentCardResponse The stored A2A agent card and the publication state that explains its presence or absence.
type A2AAgentCardResponse struct {
	// The document the gateway serves; absent or null until the first successful fetch.
	Card map[string]interface{} `json:"card,omitempty"`
	// Publication lifecycle state for this agent-environment pair.
	Status string `json:"status"`
	// When the Agent resource was last routed live. Null when the pair has never routed, which is what distinguishes \"never routed\" from \"routed, but the card never arrived\" while status is failed.
	RoutedAt NullableTime `json:"routedAt"`
	// When the stored card was last fetched successfully. Null until the first fetch.
	FetchedAt NullableTime `json:"fetchedAt"`
	// The last failure, or empty when clean.
	LastError string `json:"lastError"`
}

// NewA2AAgentCardResponse instantiates a new A2AAgentCardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewA2AAgentCardResponse(status string, routedAt NullableTime, fetchedAt NullableTime, lastError string) *A2AAgentCardResponse {
	this := A2AAgentCardResponse{}
	this.Status = status
	this.RoutedAt = routedAt
	this.FetchedAt = fetchedAt
	this.LastError = lastError
	return &this
}

// NewA2AAgentCardResponseWithDefaults instantiates a new A2AAgentCardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewA2AAgentCardResponseWithDefaults() *A2AAgentCardResponse {
	this := A2AAgentCardResponse{}
	return &this
}

// GetCard returns the Card field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *A2AAgentCardResponse) GetCard() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Card
}

// GetCardOk returns a tuple with the Card field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *A2AAgentCardResponse) GetCardOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Card) {
		return map[string]interface{}{}, false
	}
	return o.Card, true
}

// HasCard returns a boolean if a field has been set.
func (o *A2AAgentCardResponse) HasCard() bool {
	if o != nil && IsNil(o.Card) {
		return true
	}

	return false
}

// SetCard gets a reference to the given map[string]interface{} and assigns it to the Card field.
func (o *A2AAgentCardResponse) SetCard(v map[string]interface{}) {
	o.Card = v
}

// GetStatus returns the Status field value
func (o *A2AAgentCardResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *A2AAgentCardResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *A2AAgentCardResponse) SetStatus(v string) {
	o.Status = v
}

// GetRoutedAt returns the RoutedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *A2AAgentCardResponse) GetRoutedAt() time.Time {
	if o == nil || o.RoutedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.RoutedAt.Get()
}

// GetRoutedAtOk returns a tuple with the RoutedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *A2AAgentCardResponse) GetRoutedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoutedAt.Get(), o.RoutedAt.IsSet()
}

// SetRoutedAt sets field value
func (o *A2AAgentCardResponse) SetRoutedAt(v time.Time) {
	o.RoutedAt.Set(&v)
}

// GetFetchedAt returns the FetchedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *A2AAgentCardResponse) GetFetchedAt() time.Time {
	if o == nil || o.FetchedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.FetchedAt.Get()
}

// GetFetchedAtOk returns a tuple with the FetchedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *A2AAgentCardResponse) GetFetchedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.FetchedAt.Get(), o.FetchedAt.IsSet()
}

// SetFetchedAt sets field value
func (o *A2AAgentCardResponse) SetFetchedAt(v time.Time) {
	o.FetchedAt.Set(&v)
}

// GetLastError returns the LastError field value
func (o *A2AAgentCardResponse) GetLastError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value
// and a boolean to check if the value has been set.
func (o *A2AAgentCardResponse) GetLastErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastError, true
}

// SetLastError sets field value
func (o *A2AAgentCardResponse) SetLastError(v string) {
	o.LastError = v
}

func (o A2AAgentCardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o A2AAgentCardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Card != nil {
		toSerialize["card"] = o.Card
	}
	toSerialize["status"] = o.Status
	toSerialize["routedAt"] = o.RoutedAt.Get()
	toSerialize["fetchedAt"] = o.FetchedAt.Get()
	toSerialize["lastError"] = o.LastError
	return toSerialize, nil
}

type NullableA2AAgentCardResponse struct {
	value *A2AAgentCardResponse
	isSet bool
}

func (v NullableA2AAgentCardResponse) Get() *A2AAgentCardResponse {
	return v.value
}

func (v *NullableA2AAgentCardResponse) Set(val *A2AAgentCardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableA2AAgentCardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableA2AAgentCardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableA2AAgentCardResponse(val *A2AAgentCardResponse) *NullableA2AAgentCardResponse {
	return &NullableA2AAgentCardResponse{value: val, isSet: true}
}

func (v NullableA2AAgentCardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableA2AAgentCardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
