// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repomocks

import (
	"context"
	"encoding/json"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/wso2/agent-manager/agent-manager-service/models"
)

// A2APublicationRepositoryMock is a mock implementation of repositories.A2APublicationRepository.
//
//	func TestSomethingThatUsesA2APublicationRepository(t *testing.T) {
//
//		// make and configure a mocked repositories.A2APublicationRepository
//		mockedA2APublicationRepository := &A2APublicationRepositoryMock{
//			DeleteForAgentFunc: func(ctx context.Context, ouID string, projectName string, agentName string) error {
//				panic("mock out the DeleteForAgent method")
//			},
//			EnqueueFunc: func(ctx context.Context, pub *models.A2APublication) error {
//				panic("mock out the Enqueue method")
//			},
//			FindDueFunc: func(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error) {
//				panic("mock out the FindDue method")
//			},
//			GetForAgentEnvFunc: func(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) (*models.A2APublication, error) {
//				panic("mock out the GetForAgentEnv method")
//			},
//			MarkAttemptFailedFunc: func(ctx context.Context, id uuid.UUID, lastErr string, nextAttemptAt time.Time) error {
//				panic("mock out the MarkAttemptFailed method")
//			},
//			MarkCardPublishedFunc: func(ctx context.Context, id uuid.UUID, card json.RawMessage, fetchedAt time.Time) error {
//				panic("mock out the MarkCardPublished method")
//			},
//			MarkCardRejectedFunc: func(ctx context.Context, deploymentID uuid.UUID, errorCode string) error {
//				panic("mock out the MarkCardRejected method")
//			},
//			MarkFailedFunc: func(ctx context.Context, id uuid.UUID, lastErr string) error {
//				panic("mock out the MarkFailed method")
//			},
//			MarkRoutedFunc: func(ctx context.Context, id uuid.UUID, routedAt time.Time) error {
//				panic("mock out the MarkRouted method")
//			},
//			RequeueCardFunc: func(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) error {
//				panic("mock out the RequeueCard method")
//			},
//			SetCardDeploymentIDFunc: func(ctx context.Context, id uuid.UUID, deploymentID uuid.UUID) error {
//				panic("mock out the SetCardDeploymentID method")
//			},
//		}
//
//		// use mockedA2APublicationRepository in code that requires repositories.A2APublicationRepository
//		// and then make assertions.
//
//	}
type A2APublicationRepositoryMock struct {
	// DeleteForAgentFunc mocks the DeleteForAgent method.
	DeleteForAgentFunc func(ctx context.Context, ouID string, projectName string, agentName string) error

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, pub *models.A2APublication) error

	// FindDueFunc mocks the FindDue method.
	FindDueFunc func(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error)

	// GetForAgentEnvFunc mocks the GetForAgentEnv method.
	GetForAgentEnvFunc func(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) (*models.A2APublication, error)

	// MarkAttemptFailedFunc mocks the MarkAttemptFailed method.
	MarkAttemptFailedFunc func(ctx context.Context, id uuid.UUID, lastErr string, nextAttemptAt time.Time) error

	// MarkCardPublishedFunc mocks the MarkCardPublished method.
	MarkCardPublishedFunc func(ctx context.Context, id uuid.UUID, card json.RawMessage, fetchedAt time.Time) error

	// MarkCardRejectedFunc mocks the MarkCardRejected method.
	MarkCardRejectedFunc func(ctx context.Context, deploymentID uuid.UUID, errorCode string) error

	// MarkFailedFunc mocks the MarkFailed method.
	MarkFailedFunc func(ctx context.Context, id uuid.UUID, lastErr string) error

	// MarkRoutedFunc mocks the MarkRouted method.
	MarkRoutedFunc func(ctx context.Context, id uuid.UUID, routedAt time.Time) error

	// RequeueCardFunc mocks the RequeueCard method.
	RequeueCardFunc func(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) error

	// SetCardDeploymentIDFunc mocks the SetCardDeploymentID method.
	SetCardDeploymentIDFunc func(ctx context.Context, id uuid.UUID, deploymentID uuid.UUID) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteForAgent holds details about calls to the DeleteForAgent method.
		DeleteForAgent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pub is the pub argument value.
			Pub *models.A2APublication
		}
		// FindDue holds details about calls to the FindDue method.
		FindDue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Now is the now argument value.
			Now time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetForAgentEnv holds details about calls to the GetForAgentEnv method.
		GetForAgentEnv []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// EnvironmentUUID is the environmentUUID argument value.
			EnvironmentUUID uuid.UUID
		}
		// MarkAttemptFailed holds details about calls to the MarkAttemptFailed method.
		MarkAttemptFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// LastErr is the lastErr argument value.
			LastErr string
			// NextAttemptAt is the nextAttemptAt argument value.
			NextAttemptAt time.Time
		}
		// MarkCardPublished holds details about calls to the MarkCardPublished method.
		MarkCardPublished []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Card is the card argument value.
			Card json.RawMessage
			// FetchedAt is the fetchedAt argument value.
			FetchedAt time.Time
		}
		// MarkCardRejected holds details about calls to the MarkCardRejected method.
		MarkCardRejected []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeploymentID is the deploymentID argument value.
			DeploymentID uuid.UUID
			// ErrorCode is the errorCode argument value.
			ErrorCode string
		}
		// MarkFailed holds details about calls to the MarkFailed method.
		MarkFailed []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// LastErr is the lastErr argument value.
			LastErr string
		}
		// MarkRouted holds details about calls to the MarkRouted method.
		MarkRouted []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// RoutedAt is the routedAt argument value.
			RoutedAt time.Time
		}
		// RequeueCard holds details about calls to the RequeueCard method.
		RequeueCard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OuID is the ouID argument value.
			OuID string
			// ProjectName is the projectName argument value.
			ProjectName string
			// AgentName is the agentName argument value.
			AgentName string
			// EnvironmentUUID is the environmentUUID argument value.
			EnvironmentUUID uuid.UUID
		}
		// SetCardDeploymentID holds details about calls to the SetCardDeploymentID method.
		SetCardDeploymentID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// DeploymentID is the deploymentID argument value.
			DeploymentID uuid.UUID
		}
	}
	lockDeleteForAgent      sync.RWMutex
	lockEnqueue             sync.RWMutex
	lockFindDue             sync.RWMutex
	lockGetForAgentEnv      sync.RWMutex
	lockMarkAttemptFailed   sync.RWMutex
	lockMarkCardPublished   sync.RWMutex
	lockMarkCardRejected    sync.RWMutex
	lockMarkFailed          sync.RWMutex
	lockMarkRouted          sync.RWMutex
	lockRequeueCard         sync.RWMutex
	lockSetCardDeploymentID sync.RWMutex
}

// DeleteForAgent calls DeleteForAgentFunc.
func (mock *A2APublicationRepositoryMock) DeleteForAgent(ctx context.Context, ouID string, projectName string, agentName string) error {
	if mock.DeleteForAgentFunc == nil {
		panic("A2APublicationRepositoryMock.DeleteForAgentFunc: method is nil but A2APublicationRepository.DeleteForAgent was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}{
		Ctx:         ctx,
		OuID:        ouID,
		ProjectName: projectName,
		AgentName:   agentName,
	}
	mock.lockDeleteForAgent.Lock()
	mock.calls.DeleteForAgent = append(mock.calls.DeleteForAgent, callInfo)
	mock.lockDeleteForAgent.Unlock()
	return mock.DeleteForAgentFunc(ctx, ouID, projectName, agentName)
}

// DeleteForAgentCalls gets all the calls that were made to DeleteForAgent.
// Check the length with:
//
//	len(mockedA2APublicationRepository.DeleteForAgentCalls())
func (mock *A2APublicationRepositoryMock) DeleteForAgentCalls() []struct {
	Ctx         context.Context
	OuID        string
	ProjectName string
	AgentName   string
} {
	var calls []struct {
		Ctx         context.Context
		OuID        string
		ProjectName string
		AgentName   string
	}
	mock.lockDeleteForAgent.RLock()
	calls = mock.calls.DeleteForAgent
	mock.lockDeleteForAgent.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *A2APublicationRepositoryMock) Enqueue(ctx context.Context, pub *models.A2APublication) error {
	if mock.EnqueueFunc == nil {
		panic("A2APublicationRepositoryMock.EnqueueFunc: method is nil but A2APublicationRepository.Enqueue was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pub *models.A2APublication
	}{
		Ctx: ctx,
		Pub: pub,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, pub)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedA2APublicationRepository.EnqueueCalls())
func (mock *A2APublicationRepositoryMock) EnqueueCalls() []struct {
	Ctx context.Context
	Pub *models.A2APublication
} {
	var calls []struct {
		Ctx context.Context
		Pub *models.A2APublication
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// FindDue calls FindDueFunc.
func (mock *A2APublicationRepositoryMock) FindDue(ctx context.Context, now time.Time, limit int) ([]models.A2APublication, error) {
	if mock.FindDueFunc == nil {
		panic("A2APublicationRepositoryMock.FindDueFunc: method is nil but A2APublicationRepository.FindDue was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}{
		Ctx:   ctx,
		Now:   now,
		Limit: limit,
	}
	mock.lockFindDue.Lock()
	mock.calls.FindDue = append(mock.calls.FindDue, callInfo)
	mock.lockFindDue.Unlock()
	return mock.FindDueFunc(ctx, now, limit)
}

// FindDueCalls gets all the calls that were made to FindDue.
// Check the length with:
//
//	len(mockedA2APublicationRepository.FindDueCalls())
func (mock *A2APublicationRepositoryMock) FindDueCalls() []struct {
	Ctx   context.Context
	Now   time.Time
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Now   time.Time
		Limit int
	}
	mock.lockFindDue.RLock()
	calls = mock.calls.FindDue
	mock.lockFindDue.RUnlock()
	return calls
}

// GetForAgentEnv calls GetForAgentEnvFunc.
func (mock *A2APublicationRepositoryMock) GetForAgentEnv(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) (*models.A2APublication, error) {
	if mock.GetForAgentEnvFunc == nil {
		panic("A2APublicationRepositoryMock.GetForAgentEnvFunc: method is nil but A2APublicationRepository.GetForAgentEnv was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OuID            string
		ProjectName     string
		AgentName       string
		EnvironmentUUID uuid.UUID
	}{
		Ctx:             ctx,
		OuID:            ouID,
		ProjectName:     projectName,
		AgentName:       agentName,
		EnvironmentUUID: environmentUUID,
	}
	mock.lockGetForAgentEnv.Lock()
	mock.calls.GetForAgentEnv = append(mock.calls.GetForAgentEnv, callInfo)
	mock.lockGetForAgentEnv.Unlock()
	return mock.GetForAgentEnvFunc(ctx, ouID, projectName, agentName, environmentUUID)
}

// GetForAgentEnvCalls gets all the calls that were made to GetForAgentEnv.
// Check the length with:
//
//	len(mockedA2APublicationRepository.GetForAgentEnvCalls())
func (mock *A2APublicationRepositoryMock) GetForAgentEnvCalls() []struct {
	Ctx             context.Context
	OuID            string
	ProjectName     string
	AgentName       string
	EnvironmentUUID uuid.UUID
} {
	var calls []struct {
		Ctx             context.Context
		OuID            string
		ProjectName     string
		AgentName       string
		EnvironmentUUID uuid.UUID
	}
	mock.lockGetForAgentEnv.RLock()
	calls = mock.calls.GetForAgentEnv
	mock.lockGetForAgentEnv.RUnlock()
	return calls
}

// MarkAttemptFailed calls MarkAttemptFailedFunc.
func (mock *A2APublicationRepositoryMock) MarkAttemptFailed(ctx context.Context, id uuid.UUID, lastErr string, nextAttemptAt time.Time) error {
	if mock.MarkAttemptFailedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkAttemptFailedFunc: method is nil but A2APublicationRepository.MarkAttemptFailed was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ID            uuid.UUID
		LastErr       string
		NextAttemptAt time.Time
	}{
		Ctx:           ctx,
		ID:            id,
		LastErr:       lastErr,
		NextAttemptAt: nextAttemptAt,
	}
	mock.lockMarkAttemptFailed.Lock()
	mock.calls.MarkAttemptFailed = append(mock.calls.MarkAttemptFailed, callInfo)
	mock.lockMarkAttemptFailed.Unlock()
	return mock.MarkAttemptFailedFunc(ctx, id, lastErr, nextAttemptAt)
}

// MarkAttemptFailedCalls gets all the calls that were made to MarkAttemptFailed.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkAttemptFailedCalls())
func (mock *A2APublicationRepositoryMock) MarkAttemptFailedCalls() []struct {
	Ctx           context.Context
	ID            uuid.UUID
	LastErr       string
	NextAttemptAt time.Time
} {
	var calls []struct {
		Ctx           context.Context
		ID            uuid.UUID
		LastErr       string
		NextAttemptAt time.Time
	}
	mock.lockMarkAttemptFailed.RLock()
	calls = mock.calls.MarkAttemptFailed
	mock.lockMarkAttemptFailed.RUnlock()
	return calls
}

// MarkCardPublished calls MarkCardPublishedFunc.
func (mock *A2APublicationRepositoryMock) MarkCardPublished(ctx context.Context, id uuid.UUID, card json.RawMessage, fetchedAt time.Time) error {
	if mock.MarkCardPublishedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkCardPublishedFunc: method is nil but A2APublicationRepository.MarkCardPublished was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Card      json.RawMessage
		FetchedAt time.Time
	}{
		Ctx:       ctx,
		ID:        id,
		Card:      card,
		FetchedAt: fetchedAt,
	}
	mock.lockMarkCardPublished.Lock()
	mock.calls.MarkCardPublished = append(mock.calls.MarkCardPublished, callInfo)
	mock.lockMarkCardPublished.Unlock()
	return mock.MarkCardPublishedFunc(ctx, id, card, fetchedAt)
}

// MarkCardPublishedCalls gets all the calls that were made to MarkCardPublished.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkCardPublishedCalls())
func (mock *A2APublicationRepositoryMock) MarkCardPublishedCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Card      json.RawMessage
	FetchedAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ID        uuid.UUID
		Card      json.RawMessage
		FetchedAt time.Time
	}
	mock.lockMarkCardPublished.RLock()
	calls = mock.calls.MarkCardPublished
	mock.lockMarkCardPublished.RUnlock()
	return calls
}

// MarkCardRejected calls MarkCardRejectedFunc.
func (mock *A2APublicationRepositoryMock) MarkCardRejected(ctx context.Context, deploymentID uuid.UUID, errorCode string) error {
	if mock.MarkCardRejectedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkCardRejectedFunc: method is nil but A2APublicationRepository.MarkCardRejected was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		DeploymentID uuid.UUID
		ErrorCode    string
	}{
		Ctx:          ctx,
		DeploymentID: deploymentID,
		ErrorCode:    errorCode,
	}
	mock.lockMarkCardRejected.Lock()
	mock.calls.MarkCardRejected = append(mock.calls.MarkCardRejected, callInfo)
	mock.lockMarkCardRejected.Unlock()
	return mock.MarkCardRejectedFunc(ctx, deploymentID, errorCode)
}

// MarkCardRejectedCalls gets all the calls that were made to MarkCardRejected.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkCardRejectedCalls())
func (mock *A2APublicationRepositoryMock) MarkCardRejectedCalls() []struct {
	Ctx          context.Context
	DeploymentID uuid.UUID
	ErrorCode    string
} {
	var calls []struct {
		Ctx          context.Context
		DeploymentID uuid.UUID
		ErrorCode    string
	}
	mock.lockMarkCardRejected.RLock()
	calls = mock.calls.MarkCardRejected
	mock.lockMarkCardRejected.RUnlock()
	return calls
}

// MarkFailed calls MarkFailedFunc.
func (mock *A2APublicationRepositoryMock) MarkFailed(ctx context.Context, id uuid.UUID, lastErr string) error {
	if mock.MarkFailedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkFailedFunc: method is nil but A2APublicationRepository.MarkFailed was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      uuid.UUID
		LastErr string
	}{
		Ctx:     ctx,
		ID:      id,
		LastErr: lastErr,
	}
	mock.lockMarkFailed.Lock()
	mock.calls.MarkFailed = append(mock.calls.MarkFailed, callInfo)
	mock.lockMarkFailed.Unlock()
	return mock.MarkFailedFunc(ctx, id, lastErr)
}

// MarkFailedCalls gets all the calls that were made to MarkFailed.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkFailedCalls())
func (mock *A2APublicationRepositoryMock) MarkFailedCalls() []struct {
	Ctx     context.Context
	ID      uuid.UUID
	LastErr string
} {
	var calls []struct {
		Ctx     context.Context
		ID      uuid.UUID
		LastErr string
	}
	mock.lockMarkFailed.RLock()
	calls = mock.calls.MarkFailed
	mock.lockMarkFailed.RUnlock()
	return calls
}

// MarkRouted calls MarkRoutedFunc.
func (mock *A2APublicationRepositoryMock) MarkRouted(ctx context.Context, id uuid.UUID, routedAt time.Time) error {
	if mock.MarkRoutedFunc == nil {
		panic("A2APublicationRepositoryMock.MarkRoutedFunc: method is nil but A2APublicationRepository.MarkRouted was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uuid.UUID
		RoutedAt time.Time
	}{
		Ctx:      ctx,
		ID:       id,
		RoutedAt: routedAt,
	}
	mock.lockMarkRouted.Lock()
	mock.calls.MarkRouted = append(mock.calls.MarkRouted, callInfo)
	mock.lockMarkRouted.Unlock()
	return mock.MarkRoutedFunc(ctx, id, routedAt)
}

// MarkRoutedCalls gets all the calls that were made to MarkRouted.
// Check the length with:
//
//	len(mockedA2APublicationRepository.MarkRoutedCalls())
func (mock *A2APublicationRepositoryMock) MarkRoutedCalls() []struct {
	Ctx      context.Context
	ID       uuid.UUID
	RoutedAt time.Time
} {
	var calls []struct {
		Ctx      context.Context
		ID       uuid.UUID
		RoutedAt time.Time
	}
	mock.lockMarkRouted.RLock()
	calls = mock.calls.MarkRouted
	mock.lockMarkRouted.RUnlock()
	return calls
}

// RequeueCard calls RequeueCardFunc.
func (mock *A2APublicationRepositoryMock) RequeueCard(ctx context.Context, ouID string, projectName string, agentName string, environmentUUID uuid.UUID) error {
	if mock.RequeueCardFunc == nil {
		panic("A2APublicationRepositoryMock.RequeueCardFunc: method is nil but A2APublicationRepository.RequeueCard was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		OuID            string
		ProjectName     string
		AgentName       string
		EnvironmentUUID uuid.UUID
	}{
		Ctx:             ctx,
		OuID:            ouID,
		ProjectName:     projectName,
		AgentName:       agentName,
		EnvironmentUUID: environmentUUID,
	}
	mock.lockRequeueCard.Lock()
	mock.calls.RequeueCard = append(mock.calls.RequeueCard, callInfo)
	mock.lockRequeueCard.Unlock()
	return mock.RequeueCardFunc(ctx, ouID, projectName, agentName, environmentUUID)
}

// RequeueCardCalls gets all the calls that were made to RequeueCard.
// Check the length with:
//
//	len(mockedA2APublicationRepository.RequeueCardCalls())
func (mock *A2APublicationRepositoryMock) RequeueCardCalls() []struct {
	Ctx             context.Context
	OuID            string
	ProjectName     string
	AgentName       string
	EnvironmentUUID uuid.UUID
} {
	var calls []struct {
		Ctx             context.Context
		OuID            string
		ProjectName     string
		AgentName       string
		EnvironmentUUID uuid.UUID
	}
	mock.lockRequeueCard.RLock()
	calls = mock.calls.RequeueCard
	mock.lockRequeueCard.RUnlock()
	return calls
}

// SetCardDeploymentID calls SetCardDeploymentIDFunc.
func (mock *A2APublicationRepositoryMock) SetCardDeploymentID(ctx context.Context, id uuid.UUID, deploymentID uuid.UUID) error {
	if mock.SetCardDeploymentIDFunc == nil {
		panic("A2APublicationRepositoryMock.SetCardDeploymentIDFunc: method is nil but A2APublicationRepository.SetCardDeploymentID was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ID           uuid.UUID
		DeploymentID uuid.UUID
	}{
		Ctx:          ctx,
		ID:           id,
		DeploymentID: deploymentID,
	}
	mock.lockSetCardDeploymentID.Lock()
	mock.calls.SetCardDeploymentID = append(mock.calls.SetCardDeploymentID, callInfo)
	mock.lockSetCardDeploymentID.Unlock()
	return mock.SetCardDeploymentIDFunc(ctx, id, deploymentID)
}

// SetCardDeploymentIDCalls gets all the calls that were made to SetCardDeploymentID.
// Check the length with:
//
//	len(mockedA2APublicationRepository.SetCardDeploymentIDCalls())
func (mock *A2APublicationRepositoryMock) SetCardDeploymentIDCalls() []struct {
	Ctx          context.Context
	ID           uuid.UUID
	DeploymentID uuid.UUID
} {
	var calls []struct {
		Ctx          context.Context
		ID           uuid.UUID
		DeploymentID uuid.UUID
	}
	mock.lockSetCardDeploymentID.RLock()
	calls = mock.calls.SetCardDeploymentID
	mock.lockSetCardDeploymentID.RUnlock()
	return calls
}
